### PR TITLE
Update Tutorial_de_DE.lang

### PR DESCRIPTION
**Pull request by janbpunkt**
Added missing sentences; 
changed "…" to "..."; 
removed wrong whitespacings before "..."

### CODE REVIEW

**Comment by MoombaDS** [comment]
Hi!

So, from my understanding (a bit of a literary and grammar nerd even when I don't actually speak the language), the use of space before an ellipsis in German is something that's commonly misunderstood.

Based on my rudimentary knowledge, in German, an ellipsis is _always_ preceded by a space _unless_ it cuts off the word preceding it. In this case, it is the _sentence_ that is cutting off and the word is complete, therefore there should be a space before the ellipsis.

**Comment by janbpunkt** [comment]
Hi Joe,

I just re-read the according rules and it seems you're right.
My apologies.
Although the characters seems to be wrong. They were looking different in the editor. No idea, why.

Cheers,
Jan

**Comment by janbpunkt** [comment]
Okay, it seems that there's a special character for ...
But we should keep it consistent as the original sentences use triple dots instead of the special char.

**Comment by bartwe** [comment]
Manually merged the new lines, not merging the ... lines.

**Pull request closed without merging**
