### PR TITLE
Minor corrections

### PR DESCRIPTION
**Pull request by Alan-FGR**

### CODE REVIEW

**Comment by spidersouris** [comment]
I don't think you should have removed the new strings

**Comment by MoombaDS** [comment]
I think that was just bad timing on the PR, and as long as they're empty strings and not in the main translation file (en-GB) it shouldn't prove too much of an issue

**Comment by spidersouris** [comment]
oh ok, I thought he removed them intentionally :P

**Comment by Alan-FGR** [comment]
Yeah, bad timing. I thought it would be obvious. I guess you guys have some script to automatically deal with that (add the missing strings to the updated file) so I didn't took any action on that regard.

**Pull request merged**
